# 公共配置定义
_common: &common_base

  # 公共judgment配置锚点
  judgment: &common_judgment
    judgment_type: ExactMatch

  # 公共metrics配置锚点
  metrics:
    - &accuracy_metrics
      metrics_type: Accuracy
      metrics_name: Accuracy
      judgment_cfgs: *common_judgment

model_cfgs:
  model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
  inference_backend: vllm
  vllm_init_args:
    tensor_parallel_size: 4
    dtype: bfloat16
    max_model_len: 17408
    gpu_memory_utilization: 0.9
    max_num_seqs: 16
    enable_prefix_caching: true

inference_cfgs:
  sampling_params:
    max_tokens: 16384
    temperature: 0.0
    repetition_penalty: 1.2
    top_p: 0.95
    stop: ["<｜end▁of▁sentence｜>"]
    seed: 46

cache_cfgs:
  cache_type: json_file
  cache_dir: ./cache/inference
  flush_threshold: 10

eval_cfgs:
  output_dir: ./output
  benchmark_type: capability

  # Benchmarks配置
  benchmarks:
    # Benchmark 1: 完全复用公共metrics配置
    AIME:
      data_cfgs:
        data_path: Maxwell-Jia/AIME_2024
        data_template: AIME
        task_list: null
        data_size: null
        load_cfgs:
          split: train
      metrics_cfgs:
        - <<: *accuracy_metrics
          prompt_template: AIME
        - metrics_type: PassAtK
          metrics_name: PassAt3
          judgment_cfgs: *common_judgment
          prompt_template: AIME
          k: 3
    MATH:
      data_cfgs:
        data_path: ./data/MATH
        data_template: MATH
        task_list: null
        data_size: null
        load_cfgs:
          split: train
      metrics_cfgs:
        - metrics_type: Accuracy
          metrics_name: Accuracy
          judgment_cfgs: &math_judgment
            judgment_type: LLMMatch
            model_cfgs:
              inference_backend: api
              model_sdk_type: openai
              model_name_or_path: qwen-plus
              api_key_name: QWEN_API_KEY
            inference_cfgs:
              max_tokens: 4096
              max_retry: 3
              max_workers: 8
              sleep_seconds: 30
            cache_cfgs:
              cache_type: json_file
              cache_dir: ./cache/inference
              flush_threshold: 10
            prompt_template: MATH
          prompt_template: MATH
        - metrics_type: PassAtK
          metrics_name: PassAt3
          judgment_cfgs: *math_judgment
          prompt_template: MATH
          k: 3
    MATH-test:
      data_cfgs:
        data_path: ./data/MATH
        data_template: MATH
        task_list: null
        data_size: null
        load_cfgs:
          split: test
      metrics_cfgs:
        - metrics_type: Accuracy
          metrics_name: Accuracy
          judgment_cfgs: *math_judgment
          prompt_template: MATH
        - metrics_type: PassAtK
          metrics_name: PassAt3
          judgment_cfgs: *math_judgment
          prompt_template: MATH
          k: 3
