model_cfgs:
  model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
  inference_backend: vllm
  vllm_init_args:
    tensor_parallel_size: 4
    dtype: bfloat16
    max_model_len: 8192
    gpu_memory_utilization: 0.9

inference_cfgs:
  inference_batch_size: 32
  sampling_params:
    max_tokens: 8192
    temperature: 0.0
    top_k: 1
    top_p: 1.0
    stop: ["<|endoftext|>"]

cache_cfgs:
  cache_type: json_file
  cache_dir: ./cache/inference
  flush_threshold: 10

eval_cfgs:
  benchmark_type: safety

  # 公共配置定义
  _common: &common_base

    # 公共judgment配置锚点
    judgment: &common_judgment
      judgment_type: LLM
      model_cfgs:
        inference_backend: vllm
        model_name_or_path: meta-llama/Llama-Guard-3-8B
        vllm_init_args:
          tensor_parallel_size: 4
          dtype: bfloat16
          max_model_len: 8192
          max_num_seqs: 32
          gpu_memory_utilization: 0.8
      inference_cfgs:
        prompt_builder_type: LlamaGuard
        inference_batch_size: 32
        sampling_params:
          temperature: 0.0
          top_k: 1
          top_p: 1.0
          max_tokens: 10
          skip_special_tokens: true
          stop: ["<|endoftext|>"]
      cache_cfgs:
        cache_type: json_file
        cache_dir: ./cache/judgment_inference
        flush_threshold: 10

    # 公共metrics配置锚点
    metrics: &common_metrics
      - metrics_type: ASR
        metrics_name: ASR
        judgment_cfgs: *common_judgment

  # Benchmarks配置
  benchmarks:
    # Benchmark 1: 完全复用公共metrics配置
    AdvBench:
      data_cfgs:
        data_path: walledai/AdvBench
        data_name: null
        data_template: AdvBench
        split: train
        task_list: null
        data_size: null
      metrics_cfgs: *common_metrics  # 直接引用公共配置

    StrongReject:
      data_cfgs:
        data_path: walledai/StrongREJECT
        data_name: null
        data_template: StrongReject
        split: train
        task_list: null
        data_size: null
      metrics_cfgs: *common_metrics

    JBB-Behaviors:
      data_cfgs:
        data_path: JailbreakBench/JBB-Behaviors
        data_name: behaviors
        data_template: JBB-Behaviors
        split: harmful
        task_list: null
        data_size: null
      metrics_cfgs: *common_metrics

    # # Benchmark 2: 复用metrics配置但修改其中一个metric
    # CustomBench:
    #   data_name_or_path: custom/path
    #   data_template: CustomTemplate
    #   metrics_cfgs:
    #     <<: *common_metrics  # 继承整个metrics列表
    #     # 修改列表中第一个metric的特定字段
    #     - <<: *common_metrics[0]  # 继承第一个metric配置
    #       metrics_name: "Modified_ASR"  # 覆盖字段
    #       judgment_cfgs:
    #         <<: *common_judgment  # 继承judgment配置
    #         model_cfgs:
    #           model_name_or_path: "custom-model"  # 覆盖模型名称

    # # Benchmark 3: 复用metrics配置但添加新metric
    # ExtendedBench:
    #   data_name_or_path: extended/path
    #   metrics_cfgs:
    #     - *common_metrics[0]  # 复用第一个metric
    #     - metrics_type: NewMetric  # 添加新metric
    #       metrics_name: Additional_Metric
    #       # 复用公共judgment配置
    #       judgment_cfgs: *common_judgment

  attack_cfgs: []
