# 公共配置定义
_common: &common_base

  # 公共judgment配置锚点
  judgment: &common_judgment
    judgment_type: LLM
    model_cfgs:
      inference_backend: vllm
      model_name_or_path: meta-llama/Llama-Guard-3-8B
      vllm_init_args:
        tensor_parallel_size: 4
        dtype: bfloat16
        max_model_len: 8192
        max_num_seqs: 64
        gpu_memory_utilization: 0.9
        enable_prefix_caching: true
    inference_cfgs:
      sampling_params:
        temperature: 0.0
        top_k: 1
        top_p: 1.0
        max_tokens: 10
        skip_special_tokens: true
        stop: ["<｜end▁of▁sentence｜>"]
    cache_cfgs:
      cache_type: json_file
      cache_dir: ./cache/judgment_inference
      flush_threshold: 10
      force_update: false
    prompt_builder_type: LlamaGuard

  # 公共metrics配置锚点
  metrics:
    - &accuracy_metrics
      metrics_type: Accuracy
      metrics_name: ASR
      judgment_cfgs: *common_judgment

model_cfgs:
  model_name_or_path: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
  inference_backend: vllm
  vllm_init_args:
    tensor_parallel_size: 4
    dtype: bfloat16
    max_model_len: 8192
    gpu_memory_utilization: 0.9
    max_num_seqs: 64
    enable_prefix_caching: true

inference_cfgs:
  sampling_params:
    max_tokens: 8192
    temperature: 0.0
    top_k: 1
    top_p: 1.0
    stop: ["<|endoftext|>"]

cache_cfgs:
  cache_type: json_file
  cache_dir: ./cache/inference
  flush_threshold: 10
  force_update: false

eval_cfgs:
  output_dir: ./output
  benchmark_type: safety

  # Benchmarks配置
  benchmarks:
    # Benchmark 1: 完全复用公共metrics配置
    AdvBench:
      data_cfgs:
        data_path: csv
        data_template: AdvBench
        task_list: null
        data_size: null
        load_cfgs:
          data_files: https://raw.githubusercontent.com/llm-attacks/llm-attacks/refs/heads/main/data/advbench/harmful_behaviors.csv
          split: train
      metrics_cfgs:
        - *accuracy_metrics

    StrongReject:
      data_cfgs:
        data_path: csv
        data_template: StrongReject
        data_size: null
        task_list: null
        load_cfgs:
          data_files: https://raw.githubusercontent.com/alexandrasouly/strongreject/refs/heads/main/strongreject_dataset/strongreject_dataset.csv
          split: train
      metrics_cfgs:
        - *accuracy_metrics

    JBB-Behaviors:
      data_cfgs:
        data_path: JailbreakBench/JBB-Behaviors
        data_template: JBB-Behaviors
        task_list: null
        data_size: null
        load_cfgs:
          name: behaviors
          split: harmful
      metrics_cfgs:
        - *accuracy_metrics

    WildJailbreakVanilla:
      data_cfgs:
        load_type: pandas
        data_files: ./data/wildjailbreak/train/train.tsv
        data_template: wildjailbreak
        task_list: [vanilla]
        data_size: null
        read_csv_args:
          sep: "\t"
          dtype: str
      metrics_cfgs:
        - *accuracy_metrics

    WildJailbreakAdversarial:
      data_cfgs:
        load_type: pandas
        data_files: ./data/wildjailbreak/train/train.tsv
        data_template: wildjailbreak
        task_list: [adversarial]
        data_size: null
        read_csv_args:
          sep: "\t"
          dtype: str
      metrics_cfgs:
        - *accuracy_metrics

  attack_cfgs: []
